services:
  base:
    build:
      context: .
      dockerfile: environments/base/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        DEV_USER: ${DEV_USER:-devuser}
    image: dev-container-base:latest
    profiles:
      - build-only
  
  dev-container:
    build:
      context: .
      dockerfile: environments/${DEV_ENV:-base}/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        DEV_USER: ${DEV_USER:-devuser}
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      DEV_USER: ${DEV_USER:-devuser}
      TZ: ${TZ:-UTC}
      SSH_PORT: ${SSH_PORT:-2222}
    ports:
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ./workspace:/home/${DEV_USER:-devuser}/workspace
      - dev_home:/home/${DEV_USER:-marcus}
      - ./configs/common:/etc/dev/common
      - ./configs/env-specific/${DEV_ENV:-base}:/etc/dev/env-specific

volumes:
  dev_home:
    name: dev_home_${DEV_ENV:-base}
