services:
  base:
    container_name: dev-container-base
    image: dev-container-base:latest
    build:
      context: .
      dockerfile: environments/base/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        DEV_USER: ${DEV_USER:-vscode}
    env_file:
      - .env
    deploy:
      # This prevents the service from being started
      restart_policy:
        condition: none

  dev-container:
    container_name: dev-container-${DEV_ENV:-base}
    build:
      context: .
      dockerfile: environments/${DEV_ENV:-base}/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        DEV_USER: ${DEV_USER:-vscode}
    env_file:
      - .env
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      DEV_USER: ${DEV_USER:-vscode}
      TZ: ${TZ:-UTC}
      SSH_PORT: ${SSH_PORT:-2222}
      DEV_ENV: ${DEV_ENV:-base}
    ports:
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ./workspace:/home/${DEV_USER:-vscode}/workspace:rw,delegated
      - dev_home:/home/${DEV_USER:-vscode}
      # mount configs for different IDEs, or specific environments
      - ./configs/common:/etc/dev/common
      - ./configs/env-specific/${DEV_ENV:-base}:/etc/dev/env-specific
      - ide_backend_cache:/home/${DEV_USER:-vscode}/.cache/JetBrains/RemoteDev/dist

volumes:
  dev_home:
    name: dev_home_${DEV_ENV:-base}
  ide_backend_cache:
    name: ide_backend_cache_${DEV_ENV:-base}
